blank_issues_enabled: true
contact_links:
  - name: ğŸ¤” Ask a questionï¼ˆæé—®å’Œè®¨è®ºï¼‰
    url: https://github.com/zhensherlock/watermark-js-plus/discussions
    about: Ask questions and discuss with other community members
